server:
  port: 20520

spring:
  datasource:
    url: jdbc:mysql://139.155.241.99:3306/record?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 70000
      maximum-pool-size: 30
      minimum-idle: 10
      read-only: false
  jackson:
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath:mapper/*.xml
